version: '3.8'

services:
  # PostgreSQL Datenbank
  postgres:
    image: postgres:15-alpine
    container_name: software-hub-db
    environment:
      POSTGRES_DB: software_hub
      POSTGRES_USER: software_hub_user
      POSTGRES_PASSWORD: software_hub_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - software-hub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U software_hub_user -d software_hub"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Software Hub Anwendung
  app:
    build: .
    container_name: software-hub-app
    environment:
      # Datenbank Konfiguration
      DATABASE_URL: "postgresql://software_hub_user:software_hub_password@postgres:5432/software_hub"
      
      # NextAuth Konfiguration
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "your-secret-key-change-in-production"
      
      # Base URL für Embed-Codes
      NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
      
      # Node Environment
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - software-hub-network
    volumes:
      # Für Prisma Migrationen
      - ./prisma:/app/prisma
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        node server.js
      "

volumes:
  postgres_data:

networks:
  software-hub-network:
    driver: bridge
